LIBRARY ieee;
USE ieee.std_logic_1164.all;

PACKAGE gates IS

--  constant gateDelay: time := 1 ns;
  constant gateDelay: time := 0.1 ns;

END gates;




-- VHDL Entity HEIRV32_MC.mainFSM.symbol
--
-- Created:
--          by - axel.amand.UNKNOWN (WE2332101)
--          at - 09:29:07 18.10.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
-- LIBRARY gates;
use work.gates.all;

ENTITY mainFSM IS
    PORT( 
        clk       : IN     std_ulogic;
        en        : IN     std_ulogic;
        op        : IN     std_ulogic_vector (6 DOWNTO 0);
        rst       : IN     std_ulogic;
        ALUOp     : OUT    std_ulogic_vector (1 DOWNTO 0);
        ALUSrcA   : OUT    std_ulogic_vector (1 DOWNTO 0);
        ALUSrcB   : OUT    std_ulogic_vector (1 DOWNTO 0);
        IRWrite   : OUT    std_ulogic;
        PCupdate  : OUT    std_uLogic;
        adrSrc    : OUT    std_uLogic;
        branch    : OUT    std_uLogic;
        memWrite  : OUT    std_ulogic;
        regwrite  : OUT    std_ulogic;
        resultSrc : OUT    std_ulogic_vector (1 DOWNTO 0)
    );

-- Declarations

END mainFSM ;





--
-- VHDL Architecture HEIRV32_MC.mainFSM.studentVersion
--
-- Created:
--          by - axel.amand.UNKNOWN (WE7860)
--          at - 11:10:22 05.06.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
-- LIBRARY gates;
use work.gates.all;
 
ARCHITECTURE studentVersion OF mainFSM IS

    TYPE STATE_TYPE IS (
        Fetch,
        Decode,
        Execute,
        MemAccess,
        WriteBack
    );
 
    -- Declare current and next state signals
    SIGNAL current_state : STATE_TYPE;
    SIGNAL next_state : STATE_TYPE;

BEGIN

    -----------------------------------------------------------------
    clocked_proc : PROCESS ( 
        clk,
        rst
    )
    -----------------------------------------------------------------
    BEGIN
        IF (rst = '1') THEN
            current_state <= Fetch;
        ELSIF (clk'EVENT AND clk = '1') THEN
            IF (en = '1') THEN
                current_state <= next_state;
            END IF;
        END IF;
    END PROCESS clocked_proc;
 
    -----------------------------------------------------------------
    nextstate_proc : PROCESS ( 
        current_state
    )
    -----------------------------------------------------------------
    BEGIN
        CASE current_state IS
            WHEN Fetch => 
                next_state <= Decode;
            WHEN Decode => 
                next_state <= Execute;
            WHEN Execute => 
                next_state <= MemAccess;
            WHEN MemAccess => 
                next_state <= WriteBack;
            WHEN WriteBack => 
                next_state <= Fetch;
            WHEN OTHERS =>
                next_state <= Fetch;
        END CASE;
    END PROCESS nextstate_proc;
 
    -----------------------------------------------------------------
    -- Default Assignment
    ALUOp <= (others => '0');
    ALUSrcA <= (others => '0');
    ALUSrcB <= (others => '0');
    IRWrite <= '0';
    PCupdate <= '0';
    adrSrc <= '0';
    branch <= '0';
    memWrite <= '0';
    regwrite <= '0';
    resultSrc <= (others => '0');
 
END studentVersion;




